version: "3"

services:
  php:
    build:
      context: bin/${PROJECT_ENV}/php
    container_name: 'php-${PROJECT_NAME}'
    restart: 'always'
    ports:
      - ${PORT_PHP_HTTP-8080}:80
      - ${PORT_PHP_SSL-443}:443
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/${PROJECT_ENV}/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/${PROJECT_ENV}/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/${PROJECT_ENV}/apache2}:/var/log/apache2
  mysql:
    build: bin/${PROJECT_ENV}/mysql
    container_name: 'mysql-${PROJECT_NAME}'
    restart: 'always'
    ports:
      - ${PORT_MYSQL-33061}:3306
    volumes:
      - ${MYSQL_DATA_DIR-./data/${PROJECT_ENV}/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/${PROJECT_ENV}/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-${PROJECT_NAME}'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PORT_MYSQL}
    ports:
      - ${PORT_PHPMYADMIN-8090}:80
    volumes:
      - /sessions
  redis:
    container_name: 'redis-${PROJECT_NAME}'
    image: redis:latest
    ports:
      - ${PORT_REDIS-6379}:6379
