version: "3"

services:
  php:
    build:
      context: bin/${PROJECT_ENV}/php
    container_name: 'php-${PROJECT_NAME}'
    restart: 'always'
    ports:
      - ${PORT_PHP_HTTP}:80
      - ${PORT_PHP_SSL}:443
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT}/example1.com:/var/www/html/example1.com:cached
      - ${DOCUMENT_ROOT}/example2.com:/var/www/html/example2.com:cached
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-available
      - ${APACHE_LOG_DIR}:/var/log/apache2
  mysql:
    build: bin/${PROJECT_ENV}/mysql
    container_name: 'mysql-${PROJECT_NAME}'
    restart: 'always'
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin-${PROJECT_NAME}'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${PORT_MYSQL}
    ports:
      - ${PORT_PHPMYADMIN}:80
    volumes:
      - /sessions
  redis:
    container_name: 'redis-${PROJECT_NAME}'
    image: redis:latest
    ports:
      - ${PORT_REDIS}:6379
